import dotenv from "dotenv";

dotenv.config();

export const PORT = process.env.PORT || 8000;

export const MONGO_URL = process.env.MONGO_URL || "mongodb://localhost:27017";

export const ENVIRONMENT = process.env.NODE_ENV || "development";

export const FE_URL = process.env.FE_URL || "http://localhost:3000";

export const BE_URL = process.env.BE_URL || "http://localhost:8000";

export const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET || "secret";

export const RESEND_API_KEY = process.env.RESEND_API_KEY || "";

export const REFRESH_TOKEN_SECRET =
  process.env.REFRESH_TOKEN_SECRET || "secret";

export const ACCESS_TOKEN_EXPIRATION = "12h";

export const REFRESH_TOKEN_EXPIRATION = "7d";

export const RESET_TOKEN_EXPIRATION = "30m";

export const RESET_CODE_EXPIRY = 15 * 60 * 1000; // 15 minutes in milliseconds

export const PASSWORD_ENCRYPTION_LEVEL = 10;

export const ROUTES = {
  AUTH: "/auth",
  USERS: "/users",
  REFRESH: "/refresh",
} as const;

export const ROUTES_NAMES = {
  AUTH: "AUTH",
  USERS: "USERS",
  REFRESH: "REFRESH",
} as const;

export const UNIVERSAL_RESPONSE_MESSAGES = {
  200: "OK",
  500: "INTERNAL_SERVER_ERROR",
  403: "TOKEN_EXPIRED",
} as const;

export const COMMON_MESSAGES = {
  MISSING_EMAIL: "MISSING_EMAIL",
  MISSING_PASSWORD: "MISSING_PASSWORD",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  NO_REFRESH_TOKEN_PROVIDED: "NO_REFRESH_TOKEN_PROVIDED",
  REFRESH_TOKEN_NOT_FOUND: "REFRESH_TOKEN_NOT_FOUND",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  RESET_CODE_NOT_FOUND: "RESET_CODE_NOT_FOUND",
} as const;

export const RESPONSE_MESSAGES = {
  REFRESH: {
    201: "TOKEN_REFRESHED",
    400: COMMON_MESSAGES.NO_REFRESH_TOKEN_PROVIDED,
    403: COMMON_MESSAGES.INVALID_REFRESH_TOKEN,
    404: COMMON_MESSAGES.REFRESH_TOKEN_NOT_FOUND,
  },
  REGISTER: {
    201: "USER_CREATED",
    400: {
      MISSING_USERNAME: "MISSING_USERNAME",
      MISSING_EMAIL: COMMON_MESSAGES.MISSING_EMAIL,
      MISSING_PASSWORD: COMMON_MESSAGES.MISSING_PASSWORD,
    },
    403: {
      INVALID_PASSWORD: COMMON_MESSAGES.INVALID_PASSWORD,
      INVALID_EMAIL: COMMON_MESSAGES.INVALID_EMAIL,
      INVALID_USERNAME: "INVALID_USERNAME",
    },
    409: {
      USER_ALREADY_REGISTERED: "USER_ALREADY_REGISTERED",
      USERNAME_IN_NOT_UNIQUE: "USERNAME_IN_NOT_UNIQUE",
    },
  },
  LOGIN: {
    400: {
      MISSING_EMAIL: COMMON_MESSAGES.MISSING_EMAIL,
      MISSING_PASSWORD: COMMON_MESSAGES.MISSING_PASSWORD,
    },
    403: {
      INVALID_PASSWORD: COMMON_MESSAGES.INVALID_PASSWORD,
      INVALID_EMAIL: COMMON_MESSAGES.INVALID_EMAIL,
    },
    404: COMMON_MESSAGES.USER_NOT_FOUND,
  },
  LOGOUT: {
    400: COMMON_MESSAGES.NO_REFRESH_TOKEN_PROVIDED,
    404: COMMON_MESSAGES.REFRESH_TOKEN_NOT_FOUND,
  },
  REQUEST_PASSWORD_RESET: {
    400: COMMON_MESSAGES.MISSING_EMAIL,
    403: COMMON_MESSAGES.INVALID_EMAIL,
    404: COMMON_MESSAGES.USER_NOT_FOUND,
    429: "PASSWORD_RESET_RATE_LIMIT_EXCEEDED",
  },
  VERIFY_RESET_CODE: {
    400: {
      INVALID_RESET_CODE: "INVALID_RESET_CODE",
      RESET_CODE_EXPIRED: "RESET_CODE_EXPIRED",
    },
    404: {
      RESET_CODE_NOT_FOUND: COMMON_MESSAGES.RESET_CODE_NOT_FOUND,
      USER_NOT_FOUND: COMMON_MESSAGES.USER_NOT_FOUND,
      MISSING_EMAIL: COMMON_MESSAGES.MISSING_EMAIL,
    },
  },
  RESET_PASSWORD: {
    400: {
      INVALID_PASSWORD: COMMON_MESSAGES.INVALID_PASSWORD,
      INVALID_TEMP_RESET_TOKEN: "INVALID_TEMP_RESET_TOKEN",
      INVALID_EMAIL: COMMON_MESSAGES.INVALID_EMAIL,
    },
    404: {
      MISSING_PASSWORD: COMMON_MESSAGES.MISSING_PASSWORD,
      MISSING_TEMPORARY_RESET_TOKEN: "MISSING_TEMPORARY_RESET_TOKEN",
      MISSING_EMAIL: COMMON_MESSAGES.MISSING_EMAIL,
      RESET_CODE_NOT_FOUND: COMMON_MESSAGES.RESET_CODE_NOT_FOUND,
      USER_NOT_FOUND: COMMON_MESSAGES.USER_NOT_FOUND,
    },
  },
} as const;
